//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDMPro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResource_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResource_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDMPro.Resources.HomePageResource.ar", typeof(HomePageResource_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب.
        /// </summary>
        public static string AnAccount {
            get {
                return ResourceManager.GetString("AnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كثير ما تريد.
        /// </summary>
        public static string AsManyAsYouWant {
            get {
                return ResourceManager.GetString("AsManyAsYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استنساخ هذا المشروع. ثم ... نعم! لديك العديد من المشاريع الجاهزة مع بعض الميزات الموجودة..
        /// </summary>
        public static string AsManyAsYouWantDescription {
            get {
                return ResourceManager.GetString("AsManyAsYouWantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطبيق ويب ASP.NET MVC C #.
        /// </summary>
        public static string ASPNETMVCWebApplication {
            get {
                return ResourceManager.GetString("ASPNETMVCWebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فوائد.
        /// </summary>
        public static string Benefits {
            get {
                return ResourceManager.GetString("Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوالب موقع Bootstrap HTML.
        /// </summary>
        public static string BootstrapHTMLWebsiteTemplates {
            get {
                return ResourceManager.GetString("BootstrapHTMLWebsiteTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدمو CRUD.
        /// </summary>
        public static string CRUDUsers {
            get {
                return ResourceManager.GetString("CRUDUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توثيق مفصل.
        /// </summary>
        public static string DetailedDocumentation {
            get {
                return ResourceManager.GetString("DetailedDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد إلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان البريد الإلكتروني.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محفظة Envato.
        /// </summary>
        public static string EnvatoPortfolio {
            get {
                return ResourceManager.GetString("EnvatoPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليمات.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم ، هذا في خطتنا ، لكن في الوقت الحالي ، لا يمكننا ضمان وقت الإصدار..
        /// </summary>
        public static string FAQFourAnswer {
            get {
                return ResourceManager.GetString("FAQFourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل يمكنك إنشاء إصدار .NET Core MVC؟.
        /// </summary>
        public static string FAQFourQuestion {
            get {
                return ResourceManager.GetString("FAQFourQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نقدم الدعم فقط لإصلاح الأخطاء الموجودة في القوالب والإجابة على الأسئلة المتعلقة بالميزات الحالية. إرشادات خطوة بخطوة حول كيفية إجراء تعديلاتك المخصصة ، وكيفية حل الأخطاء بعد التعديلات الخاصة بك والتثبيت المباشر ليست جزءًا من دعمنا. شكرا جزيلا لتفهمك. سنقضي وقتنا في إنشاء المزيد من القوالب الرائعة لك..
        /// </summary>
        public static string FAQOneAnswer {
            get {
                return ResourceManager.GetString("FAQOneAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف هي سياسة الدعم؟.
        /// </summary>
        public static string FAQOneQuestion {
            get {
                return ResourceManager.GetString("FAQOneQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم تستطيع. انتقل إلى &quot;/Views/Shared/_FooterBeforeLogin.cshtml&quot; وابحث عن قسم التذييل لتحرير نص حقوق النشر أو إزالته..
        /// </summary>
        public static string FAQThreeAnswer {
            get {
                return ResourceManager.GetString("FAQThreeAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل يمكنني تعديل أو إزالة نص حقوق النشر في التذييل؟.
        /// </summary>
        public static string FAQThreeQuestion {
            get {
                return ResourceManager.GetString("FAQThreeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجواب: مباشرة بعد الشراء..
        /// </summary>
        public static string FAQTwoAnswerPartOne {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لمزيد من المعلومات ، يوجد قسم &quot;تنزيل العناصر الخاصة بك&quot; في نهاية هذه المقالة..
        /// </summary>
        public static string FAQTwoAnswerPartTwo {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متى يمكنني تنزيل الملف بعد شراء العنصر؟.
        /// </summary>
        public static string FAQTwoQuestion {
            get {
                return ResourceManager.GetString("FAQTwoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمات.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الميزات الأساسية الكاملة اللازمة لبدء مشروع تطبيق ويب ASP.NET MVC.
        /// </summary>
        public static string FeaturesDescription {
            get {
                return ResourceManager.GetString("FeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to املأ بياناتك للتسجيل..
        /// </summary>
        public static string Fillyourdetailstoregister {
            get {
                return ResourceManager.GetString("Fillyourdetailstoregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to املأ اسم المستخدم وكلمة المرور لتسجيل الدخول..
        /// </summary>
        public static string Fillyourusernameandpasswordtosignin {
            get {
                return ResourceManager.GetString("Fillyourusernameandpasswordtosignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تابعنا.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تابع وسائل التواصل الاجتماعي الخاصة بنا للحصول على التحديثات أو الأخبار حول المشاريع..
        /// </summary>
        public static string FollowUsDescription {
            get {
                return ResourceManager.GetString("FollowUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق النشر 2022 Hieu Dat. كل الحقوق محفوظة..
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت رقمك السري؟.
        /// </summary>
        public static string Forgotyourpassword {
            get {
                return ResourceManager.GetString("Forgotyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسئلة مكررة.
        /// </summary>
        public static string FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("FrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود المصدر الكامل.
        /// </summary>
        public static string FullSourceCode {
            get {
                return ResourceManager.GetString("FullSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استجابة تامة.
        /// </summary>
        public static string FullyResponsive {
            get {
                return ResourceManager.GetString("FullyResponsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسكن.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا هو تطبيق ويب ASP.NET MVC C # مع .NET Core 6. يساعد على بدء مشروعك ببعض الوحدات الأساسية.
        /// </summary>
        public static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDMPro- قالب بدء تطبيق الويب ASP.NET MVC C #.
        /// </summary>
        public static string HomeIndexTabTitle {
            get {
                return ResourceManager.GetString("HomeIndexTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابدأ مشروعك .net بسهولة باستخدام.
        /// </summary>
        public static string HomeTitleOne {
            get {
                return ResourceManager.GetString("HomeTitleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج.
        /// </summary>
        public static string HomeTitleTwo {
            get {
                return ResourceManager.GetString("HomeTitleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استيراد و تصدير.
        /// </summary>
        public static string ImportAndExport {
            get {
                return ResourceManager.GetString("ImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تضمين الصفحة الرئيسية.
        /// </summary>
        public static string IncludeHomePage {
            get {
                return ResourceManager.GetString("IncludeHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لن تحصل على لوحة تحكم المسؤول فحسب ، بل ستحصل أيضًا على تصميم قياسي للصفحة الرئيسية مثل هذا..
        /// </summary>
        public static string IncludeHomePageDescription {
            get {
                return ResourceManager.GetString("IncludeHomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقالات الأسئلة الشائعة حول BDMPro.
        /// </summary>
        public static string NetStarterFAQArticles {
            get {
                return ResourceManager.GetString("NetStarterFAQArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتجاتنا.
        /// </summary>
        public static string OurProducts {
            get {
                return ResourceManager.GetString("OurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string RegisterAndLogin {
            get {
                return ResourceManager.GetString("RegisterAndLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرنى؟.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذن الدور.
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وفر وقتك.
        /// </summary>
        public static string SaveYourTime {
            get {
                return ResourceManager.GetString("SaveYourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت قيم. يمكن لـ BDMPro توفير وقتك وأموالك من خلال تسريع عملية التطوير الأولية..
        /// </summary>
        public static string SaveYourTimeDescription {
            get {
                return ResourceManager.GetString("SaveYourTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال البريد الإلكتروني.
        /// </summary>
        public static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتراك.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تطويره باستخدام أحدث إطار عمل مستقر أو مكتبات.
        /// </summary>
        public static string SpecificationsDescription {
            get {
                return ResourceManager.GetString("SpecificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة الإدارة القياسية.
        /// </summary>
        public static string StandardAdminPanel {
            get {
                return ResourceManager.GetString("StandardAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية القياسية.
        /// </summary>
        public static string StandardHomePage {
            get {
                return ResourceManager.GetString("StandardHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدعم من المطور (تم تطبيق سياسة الدعم).
        /// </summary>
        public static string Supportfromdeveloper {
            get {
                return ResourceManager.GetString("Supportfromdeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقال التالي.
        /// </summary>
        public static string TheFollowingArticle {
            get {
                return ResourceManager.GetString("TheFollowingArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى BDMPro.
        /// </summary>
        public static string ToNetStarter {
            get {
                return ResourceManager.GetString("ToNetStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع ملف.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روابط مفيدة.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخططات مختلفة.
        /// </summary>
        public static string VariousCharts {
            get {
                return ResourceManager.GetString("VariousCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضوابط شكل مختلفة.
        /// </summary>
        public static string VariousFormControls {
            get {
                return ResourceManager.GetString("VariousFormControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض المزيد.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نت ستارتر.
        /// </summary>
        public static string WebAppTitle {
            get {
                return ResourceManager.GetString("WebAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to على ماذا حصلت.
        /// </summary>
        public static string Whatyouget {
            get {
                return ResourceManager.GetString("Whatyouget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد الشراء ، ستحصل على ملف مضغوط يحتوي على ما يلي.
        /// </summary>
        public static string WhatyougetDescription {
            get {
                return ResourceManager.GetString("WhatyougetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لماذا BDMPro.
        /// </summary>
        public static string WhyNetStarter {
            get {
                return ResourceManager.GetString("WhyNetStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابدأ مشروعك مع إدارة المستخدم ، إذن الدور والمزيد.
        /// </summary>
        public static string WhyNetStarterLargeTitle {
            get {
                return ResourceManager.GetString("WhyNetStarterLargeTitle", resourceCulture);
            }
        }
    }
}
