//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDMPro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResource_ms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResource_ms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDMPro.Resources.HomePageResource.ms", typeof(HomePageResource_ms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akaun.
        /// </summary>
        public static string AnAccount {
            get {
                return ResourceManager.GetString("AnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sebanyak Yang Anda Mahukan.
        /// </summary>
        public static string AsManyAsYouWant {
            get {
                return ResourceManager.GetString("AsManyAsYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klonkan projek ini. Kemudian... Ya! Anda mempunyai beberapa projek sedia dengan beberapa ciri sedia ada..
        /// </summary>
        public static string AsManyAsYouWantDescription {
            get {
                return ResourceManager.GetString("AsManyAsYouWantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikasi Web ASP.NET MVC C#.
        /// </summary>
        public static string ASPNETMVCWebApplication {
            get {
                return ResourceManager.GetString("ASPNETMVCWebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faedah.
        /// </summary>
        public static string Benefits {
            get {
                return ResourceManager.GetString("Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templat Laman Web HTML Bootstrap.
        /// </summary>
        public static string BootstrapHTMLWebsiteTemplates {
            get {
                return ResourceManager.GetString("BootstrapHTMLWebsiteTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahkan kata laluan.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pengguna CRUD.
        /// </summary>
        public static string CRUDUsers {
            get {
                return ResourceManager.GetString("CRUDUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentasi Terperinci.
        /// </summary>
        public static string DetailedDocumentation {
            get {
                return ResourceManager.GetString("DetailedDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mel.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alamat emel.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio Envato.
        /// </summary>
        public static string EnvatoPortfolio {
            get {
                return ResourceManager.GetString("EnvatoPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soalan Lazim.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya, ia ada dalam rancangan kami, tetapi buat masa ini, kami tidak dapat menjamin masa keluaran..
        /// </summary>
        public static string FAQFourAnswer {
            get {
                return ResourceManager.GetString("FAQFourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolehkah anda mencipta versi .NET Core MVC?.
        /// </summary>
        public static string FAQFourQuestion {
            get {
                return ResourceManager.GetString("FAQFourQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kami hanya menyediakan sokongan untuk membetulkan pepijat sedia ada dalam templat dan menjawab soalan mengenai ciri sedia ada. Panduan langkah demi langkah tentang cara melakukan pengubahsuaian tersuai anda, cara menyelesaikan pepijat selepas pengubahsuaian anda sendiri dan pemasangan terus bukan sebahagian daripada sokongan kami. Terima kasih banyak atas pemahaman anda. Kami akan menghabiskan masa kami untuk mencipta templat yang lebih hebat untuk anda..
        /// </summary>
        public static string FAQOneAnswer {
            get {
                return ResourceManager.GetString("FAQOneAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bagaimanakah dasar sokongan?.
        /// </summary>
        public static string FAQOneQuestion {
            get {
                return ResourceManager.GetString("FAQOneQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya awak boleh. Pergi ke &quot;/Views/Shared/_FooterBeforeLogin.cshtml&quot; dan cari bahagian pengaki untuk mengedit atau mengalih keluar teks hak cipta..
        /// </summary>
        public static string FAQThreeAnswer {
            get {
                return ResourceManager.GetString("FAQThreeAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolehkah saya mengedit atau mengalih keluar teks Hak Cipta di pengaki?.
        /// </summary>
        public static string FAQThreeQuestion {
            get {
                return ResourceManager.GetString("FAQThreeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jawapannya ialah: Sejurus selepas pembelian..
        /// </summary>
        public static string FAQTwoAnswerPartOne {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untuk mendapatkan maklumat lanjut, terdapat bahagian &quot;Memuat turun item anda&quot; di penghujung artikel ini..
        /// </summary>
        public static string FAQTwoAnswerPartTwo {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilakah saya boleh memuat turun fail selepas membeli item tersebut?.
        /// </summary>
        public static string FAQTwoQuestion {
            get {
                return ResourceManager.GetString("FAQTwoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ciri-ciri.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciri Penting Penuh Diperlukan Untuk Memulakan Projek Apl Web MVC ASP.NET.
        /// </summary>
        public static string FeaturesDescription {
            get {
                return ResourceManager.GetString("FeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isikan butiran anda untuk mendaftar..
        /// </summary>
        public static string Fillyourdetailstoregister {
            get {
                return ResourceManager.GetString("Fillyourdetailstoregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isikan nama pengguna dan kata laluan anda untuk log masuk..
        /// </summary>
        public static string Fillyourusernameandpasswordtosignin {
            get {
                return ResourceManager.GetString("Fillyourusernameandpasswordtosignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikut kami.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikuti media sosial kami untuk mendapatkan kemas kini atau berita tentang projek..
        /// </summary>
        public static string FollowUsDescription {
            get {
                return ResourceManager.GetString("FollowUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hak Cipta 2022 Hieu Dat. Hak cipta terpelihara..
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terlupa kata laluan anda?.
        /// </summary>
        public static string Forgotyourpassword {
            get {
                return ResourceManager.GetString("Forgotyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soalan Lazim.
        /// </summary>
        public static string FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("FrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Sumber Penuh.
        /// </summary>
        public static string FullSourceCode {
            get {
                return ResourceManager.GetString("FullSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsif Sepenuhnya.
        /// </summary>
        public static string FullyResponsive {
            get {
                return ResourceManager.GetString("FullyResponsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumah.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini ialah Aplikasi Web C# ASP.NET MVC dengan .NET Core 6. Ia membantu untuk memulakan projek anda dengan beberapa modul penting.
        /// </summary>
        public static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDMPro- Templat Pemula Aplikasi Web ASP.NET MVC C#.
        /// </summary>
        public static string HomeIndexTabTitle {
            get {
                return ResourceManager.GetString("HomeIndexTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulakan projek .net anda dengan mudah dengan.
        /// </summary>
        public static string HomeTitleOne {
            get {
                return ResourceManager.GetString("HomeTitleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to templat.
        /// </summary>
        public static string HomeTitleTwo {
            get {
                return ResourceManager.GetString("HomeTitleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksport import.
        /// </summary>
        public static string ImportAndExport {
            get {
                return ResourceManager.GetString("ImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sertakan Halaman Utama.
        /// </summary>
        public static string IncludeHomePage {
            get {
                return ResourceManager.GetString("IncludeHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda bukan sahaja akan mendapat papan pemuka pentadbir, tetapi juga reka bentuk halaman utama standard seperti ini..
        /// </summary>
        public static string IncludeHomePageDescription {
            get {
                return ResourceManager.GetString("IncludeHomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log masuk.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel Soalan Lazim BDMPro.
        /// </summary>
        public static string NetStarterFAQArticles {
            get {
                return ResourceManager.GetString("NetStarterFAQArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produk kami.
        /// </summary>
        public static string OurProducts {
            get {
                return ResourceManager.GetString("OurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kata laluan.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daftar &amp; Log Masuk.
        /// </summary>
        public static string RegisterAndLogin {
            get {
                return ResourceManager.GetString("RegisterAndLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingat saya?.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kebenaran Peranan.
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jimat Masa Anda.
        /// </summary>
        public static string SaveYourTime {
            get {
                return ResourceManager.GetString("SaveYourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa adalah wang. BDMPro boleh menjimatkan masa dan wang anda dengan mempercepatkan proses pembangunan awal..
        /// </summary>
        public static string SaveYourTimeDescription {
            get {
                return ResourceManager.GetString("SaveYourTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menghantar E-mel.
        /// </summary>
        public static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daftar.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spesifikasi.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dibangunkan Dengan Rangka Kerja Stabil Terkini Atau Perpustakaan.
        /// </summary>
        public static string SpecificationsDescription {
            get {
                return ResourceManager.GetString("SpecificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Pentadbiran Standard.
        /// </summary>
        public static string StandardAdminPanel {
            get {
                return ResourceManager.GetString("StandardAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halaman Utama Standard.
        /// </summary>
        public static string StandardHomePage {
            get {
                return ResourceManager.GetString("StandardHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hantar.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sokongan daripada pembangun (Dasar sokongan digunakan).
        /// </summary>
        public static string Supportfromdeveloper {
            get {
                return ResourceManager.GetString("Supportfromdeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artikel berikut.
        /// </summary>
        public static string TheFollowingArticle {
            get {
                return ResourceManager.GetString("TheFollowingArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kepada BDMPro.
        /// </summary>
        public static string ToNetStarter {
            get {
                return ResourceManager.GetString("ToNetStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muat Naik Fail.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pautan Berguna.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama pengguna.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelbagai Carta.
        /// </summary>
        public static string VariousCharts {
            get {
                return ResourceManager.GetString("VariousCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelbagai Kawalan Borang.
        /// </summary>
        public static string VariousFormControls {
            get {
                return ResourceManager.GetString("VariousFormControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat Lagi.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDMPro.
        /// </summary>
        public static string WebAppTitle {
            get {
                return ResourceManager.GetString("WebAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apa yang kamu dapat.
        /// </summary>
        public static string Whatyouget {
            get {
                return ResourceManager.GetString("Whatyouget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selepas Membeli, Anda Akan Mendapat Fail Zip Yang Mengandungi Perkara Berikut.
        /// </summary>
        public static string WhatyougetDescription {
            get {
                return ResourceManager.GetString("WhatyougetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengapa BDMPro.
        /// </summary>
        public static string WhyNetStarter {
            get {
                return ResourceManager.GetString("WhyNetStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulakan Projek Anda Dengan Pengurusan Pengguna, Kebenaran Peranan &amp; Banyak Lagi.
        /// </summary>
        public static string WhyNetStarterLargeTitle {
            get {
                return ResourceManager.GetString("WhyNetStarterLargeTitle", resourceCulture);
            }
        }
    }
}
